print("Masukan nilai a : ")
a = input()
print("Masukan nilai b : ")
b = input()
hasilq = a + b
hasilw = int(a) - int(b)
hasile = int(a) * int(b)
hasilr = int(a) / int(b)
hasild = int(a) % int(b)
print("hasil = " + str(hasilq))
print("hasil = " + str(hasilw))
print("hasil = " + str(hasile))
print("hasil = " + str(hasilr))
print("hasil = " + str(hasild))